# Generated by Django 3.2.16 on 2023-12-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
            ],
        ),
    ]
