# Generated by Django 3.2.16 on 2023-12-12 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram_api', '0003_auto_20231212_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_favorited',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_in_shopping_cart',
        ),
    ]
