# Generated by Django 3.2.16 on 2023-12-23 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foodgram_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='foodgram_api.RecipeIngredient', to='foodgram_api.Ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', to='foodgram_api.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('name', 'measurement_unit')},
        ),
        migrations.AddField(
            model_name='favoritesrecipe',
            name='favorites',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritesrecipe', to='foodgram_api.favorites'),
        ),
        migrations.AddField(
            model_name='favoritesrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritesrecipe', to='foodgram_api.recipe'),
        ),
        migrations.AddField(
            model_name='favorites',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favorites',
            name='recipe',
            field=models.ManyToManyField(related_name='favorites_recipes', through='foodgram_api.FavoritesRecipe', to='foodgram_api.Recipe'),
        ),
        migrations.AddField(
            model_name='checklistrecipe',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklistrecipe', to='foodgram_api.checklist'),
        ),
        migrations.AddField(
            model_name='checklistrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklistrecipe', to='foodgram_api.recipe'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklist',
            name='recipe',
            field=models.ManyToManyField(related_name='checklist_recipes', through='foodgram_api.CheckListRecipe', to='foodgram_api.Recipe'),
        ),
    ]
