# Generated by Django 3.2.16 on 2023-12-28 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram_api', '0004_auto_20231225_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Время приготовления должнобыть не менее 1 минуты'), django.core.validators.MaxValueValidator(10080, message='Время приготовления должнобыть более 10080 минут')], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Ингредиентов должно быть1 или более'), django.core.validators.MaxValueValidator(32767, message='Ингредиентов должно бытьне больше 32767')]),
        ),
    ]
