# Generated by Django 3.2.16 on 2023-12-28 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram_api', '0007_alter_recipe_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Ингредиентов должно быть1 или более'), django.core.validators.MaxValueValidator(32767, message='Ингредиентов должно бытьне больше 32767')]),
        ),
    ]
