# Generated by Django 3.2.16 on 2023-12-28 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20231228_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='user_follow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertofollow', to=settings.AUTH_USER_MODEL, verbose_name='Подписан на'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'user_follow'), name='no_self_subscriptions'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('user', django.db.models.expressions.F('user_follow')), _negated=True), name='unique_subscriptions'),
        ),
    ]
